### ISSUE TITLE
Не устанавливается Sharp

### ISSUE THREAD

**Issue by totaku** [andreyalexeich/gulp-pug-starter#117]
Из-за этой ошибки ни как не могу установить пакеты вашей сборки. Помогите. Использую macOS и node 14.

```
error /.../pug/node_modules/favicons/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /.../pug/node_modules/favicons/node_modules/sharp
Output:
info sharp Detected globally-installed libvips v8.10.6
info sharp Building from source via node-gyp
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.17.0 | darwin | x64
gyp info find Python using Python version 2.7.17 found at "/usr/local/opt/python@2/bin/python2.7"
gyp info spawn /usr/local/opt/python@2/bin/python2.7
gyp info spawn args [
gyp info spawn args   '/usr/local/Cellar/node@14/14.17.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/.../pug/node_modules/favicons/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/Cellar/node@14/14.17.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/.../Library/Caches/node-gyp/14.17.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/.../Library/Caches/node-gyp/14.17.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/Cellar/node@14/14.17.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/.../Library/Caches/node-gyp/14.17.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/.../pug/node_modules/favicons/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/Cellar/node@14/14.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/Cellar/node@14/14.17.0/bin/node" "/usr/local/Cellar/node@14/14.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /.../pug/node_modules/favicons/node_modules/sharp
```

**Comment by Gorotto** [comment]
@totaku попробуй "npm i"
p.s. для корректной работы нужна 12 версия nodejs

**Comment by totaku** [comment]
@Gorotto оно с какого то раза и с такой то матерью завелось.

**Comment by inkShio** [comment]
В package.json
`"gulp-favicons": "^3.0.0"`
Обнови и должно заработать

**Comment by totaku** [comment]
@inkShio не помогло, а откатывать ноду с 14 на 12 не хочу.

**Comment by inkShio** [comment]
@totaku только сейчас была такая же ошибка. Нода 14, Windows.

**Comment by totaku** [comment]
@inkShio круто) мне на маке так и не удалось завести)

**Comment by Sellato** [comment]
Завел на Linux :)

NodeJS - 14.13.1

тоже была проблема с `sharp` но в ошибке было указано решение, удалите руками пакет `sharp` и выполните `npm install` после этого все прочихалось и завелось, надеюсь навсегда.

А вообще `NodeJS v14.13.1` волшебный релиз, на нем почти все, что не работало, начинает работать :)

Удачи!
